//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ix.Palantir.Vkontakte.API.Responses.LikeShareFeed
{
    using System;
    using System.Xml.Serialization;

    public partial class response
    {
        [NonSerialized]
        private string feed;

        [XmlIgnore]
        public string Feed
        {
            get
            {
                return this.feed;
            }
            set
            {
                this.feed = value;
            }
        }

        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentObjectId { get; set; }

        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int LikeShareType { get; set; }
    }
}