//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Ix.Palantir.Vkontakte.API.Responses.NewsFeed
{
    public partial class response
    {
        public Ix.Palantir.Vkontakte.API.Responses.NewsFeed.responseItemsItem[] GroupPosts
        {
            get
            {
                responseItems responseItems = (Ix.Palantir.Vkontakte.API.Responses.NewsFeed.responseItems) this.Items[0];
                return responseItems.item ?? new Ix.Palantir.Vkontakte.API.Responses.NewsFeed.responseItemsItem[0];
            }
        }
    }
}